import {
  SiJavascript,
  SiNextdotjs,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiFlutter,
  SiFirebase,
  SiSupabase,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiOpenai,
  SiFigma,
  SiFramer,
  SiWebflow,
  SiWordpress,
  SiVercel,
} from "react-icons/si";
import { TbBrandReactNative, TbBrandAzure } from "react-icons/tb";

export const TECH_STACK = {
  nextjs: {
    name: "Next.js",
    icon: <SiNextdotjs />,
    color: "text-gray-900",
    siteUrl: "https://nextjs.org/",
  },
  reactjs: {
    name: "React.js",
    icon: <SiReact />,
    color: "text-blue-500",
    siteUrl: "https://reactjs.org/",
  },
  typescript: {
    name: "TypeScript",
    icon: <SiTypescript />,
    color: "text-blue-600",
    siteUrl: "https://www.typescriptlang.org/",
  },
  javascript: {
    name: "JavaScript",
    icon: <SiJavascript />,
    color: "text-yellow-400",
    siteUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  tailwindcss: {
    name: "Tailwind CSS",
    icon: <SiTailwindcss />,
    color: "text-cyan-500",
    siteUrl: "https://tailwindcss.com/",
  },
  reactnative: {
    name: "React Native",
    icon: <TbBrandReactNative />,
    color: "text-blue-500",
    siteUrl: "https://reactnative.dev/",
  },
  flutter: {
    name: "Flutter",
    icon: <SiFlutter />,
    color: "text-sky-400",
    siteUrl: "https://flutter.dev/",
  },
  nodejs: {
    name: "Node.js",
    icon: <SiNodedotjs />,
    color: "text-green-500",
    siteUrl: "https://nodejs.org/",
  },
  expressjs: {
    name: "Express.js",
    icon: <SiExpress />,
    color: "text-gray-700",
    siteUrl: "https://expressjs.com/",
  },
  firebase: {
    name: "Firebase",
    icon: <SiFirebase />,
    color: "text-yellow-500",
    siteUrl: "https://firebase.google.com/",
  },
  supabase: {
    name: "Supabase",
    icon: <SiSupabase />,
    color: "text-emerald-500",
    siteUrl: "https://supabase.com/",
  },
  postgresql: {
    name: "PostgreSQL",
    icon: <SiPostgresql />,
    color: "text-blue-700",
    siteUrl: "https://www.postgresql.org/",
  },
  openai: {
    name: "OpenAI API",
    icon: <SiOpenai />,
    color: "text-gray-800",
    siteUrl: "https://openai.com/",
  },
  figma: {
    name: "Figma",
    icon: <SiFigma />,
    color: "text-purple-500",
    siteUrl: "https://figma.com/",
  },
  framer: {
    name: "Framer",
    icon: <SiFramer />,
    color: "text-indigo-500",
    siteUrl: "https://framer.com/",
  },
  webflow: {
    name: "Webflow",
    icon: <SiWebflow />,
    color: "text-blue-600",
    siteUrl: "https://webflow.com/",
  },
  wordpress: {
    name: "WordPress",
    icon: <SiWordpress />,
    color: "text-sky-700",
    siteUrl: "https://wordpress.org/",
  },
  vercel: {
    name: "Vercel",
    icon: <SiVercel />,
    color: "text-gray-900",
    siteUrl: "https://vercel.com/",
  },
  azure: {
    name: "Azure",
    icon: <TbBrandAzure />,
    color: "text-blue-500",
    siteUrl: "https://azure.microsoft.com/",
  },
} satisfies Record<string, TechStack>;
